
### model
model_name_or_path: ../../hf_models/Qwen/Qwen2.5-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: gsm8k
template: qwen
cutoff_len: 512
max_samples: 100000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/gsm8k/qwen2.5-3B/lora_sft
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 64
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

## Logging
report_to: wandb
run_name: gsm8k_qwen2.5-3B_lora_sft_lr=1e-5_bs=1_ep=3

### eval
val_size: 256
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
